# Generated by Django 5.2 on 2025-04-20 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_inventarioproducto'),
        ('pedidos', '0002_alter_pedidoproducto_producto'),
        ('productos', '0001_initial'),
        ('sede', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.AddField(
            model_name='inventarioproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto'),
        ),
        migrations.AddField(
            model_name='inventarioproducto',
            name='sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sede.sede'),
        ),
    ]
