# Generated by Django 5.2 on 2025-04-23 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_delete_producto_inventarioproducto_producto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventarioproducto',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
