# Generated by Django 5.2 on 2025-04-25 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sede', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroMesa', models.PositiveIntegerField(unique=True)),
                ('capacidad', models.PositiveIntegerField()),
                ('ubicacion', models.IntegerField(choices=[(1, 'Primer piso'), (2, 'Segundo piso')])),
                ('ocupada', models.BooleanField(default=False)),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sede.sede')),
            ],
        ),
    ]
