# Generated by Django 5.2 on 2025-04-25 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesa', '0001_initial'),
        ('sede', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesa',
            name='numeroMesa',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='mesa',
            unique_together={('numeroMesa', 'sede')},
        ),
    ]
