# Generated by Django 5.2 on 2025-04-23 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_alter_pedidoproducto_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoproducto',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('preparando', 'Preparando'), ('servido', 'Servido'), ('pagado', 'Pagado')], default='pendiente', max_length=20),
        ),
    ]
