# Generated by Django 5.2 on 2025-04-25 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesa', '0002_alter_mesa_numeromesa_alter_mesa_unique_together'),
        ('pedidos', '0004_pedido_pagado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='mesa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mesa.mesa'),
        ),
    ]
