# Generated by Django 5.2 on 2025-04-23 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historial', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historialprecio',
            old_name='precio',
            new_name='precio_compra',
        ),
        migrations.AddField(
            model_name='historialprecio',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
